---
title: "Weight of Fish"
author: "Chi Nguyen"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
require(car)
require(leaps)
Fish <- read.csv(file="Fish.csv")
```








# Predicting Fish Weight

```{r}
Fish <- Fish %>%

mutate(across(where(is.character), as.factor))

levels(Fish$Species)
```



```{r}
Bream <- filter(Fish, Species == "Bream")

Bream <- select(Bream, -Species) 

Parkki <- filter(Fish, Species == "Parkki")

Parkki <- select(Parkki, -Species) 

Perch <- filter(Fish, Species == "Perch")

Perch <- select(Perch, -Species) 

Pike <- filter(Fish, Species == "Pike")

Pike <- select(Pike, -Species)

Roach <- filter(Fish, Species == "Roach")

Roach <- select(Roach, -Species) 

Smelt <- filter(Fish, Species == "Smelt")

Smelt <- select(Smelt, -Species) 

Whitefish <- filter(Fish, Species == "Whitefish")

Whitefish <- select(Whitefish, -Species) 
```


## Perch

```{r}
regsubsets.out <-

    regsubsets(Weight ~ .,

               data = Perch,

               nbest = 

1,       

# 1 best model for each number of predictors

               nvmax = 

NULL,    

# NULL for no limit on number of variables

               force.in = 

NULL, force.out = 

NULL,

               method = 

"exhaustive")

summary.out <- summary(regsubsets.out)

as.data.frame(summary.out$outmat)


```

```{r}
library(leaps)

regsubsets.out <-

    regsubsets(Weight ~ .,

               data = Perch,

               nbest = 1,       # 1 best model for each number of predictors

               nvmax = NULL,    # NULL for no limit on number of variables

               force.in = NULL, force.out = NULL,

               method = "exhaustive")

 

summary.out <- summary(regsubsets.out)

as.data.frame(summary.out$outmat)

library(car)

subsets(regsubsets.out,statistic="adjr2",legend="topright",main="Adjusted R^2")


```

Perch model 

```{r}
Perchmodel <- lm(Weight ~Height+Width, data=Perch)
summary.lm(Perchmodel)
```


The best model based on this graph is the Perch model





### Best Models

### Best Two regressor model


## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements